
import os
from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt

def parse_markdown_to_slides(md_content: str, prs):
    """
    Parse a Markdown string and add slides to the Presentation object.
    Simplistic parser:
    - # Header 1 -> Title Slide
    - ## Header 2 -> Title and Content Slide
    - Other text -> Appended to current content
    """
    lines = md_content.split('\n')
    current_slide = None
    text_frame = None

    # Layout indices (common in default template):
    # 0: Title Slide
    # 1: Title and Content
    # 2: Section Header
    
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
            
        if stripped.startswith('# '):
            # Title Slide (or Section Header if in middle)
            # Use Section Header for H1
            layout = prs.slide_layouts[2] 
            current_slide = prs.slides.add_slide(layout)
            title = current_slide.shapes.title
            title.text = stripped[2:].strip()
            # Reset text frame
            text_frame = None
            
        elif stripped.startswith('## '):
            # Content Slide
            layout = prs.slide_layouts[1]
            current_slide = prs.slides.add_slide(layout)
            title = current_slide.shapes.title
            title.text = stripped[3:].strip()
            # Get output placeholder
            body_shape = current_slide.placeholders[1]
            text_frame = body_shape.text_frame
            text_frame.word_wrap = True
            
        else:
            # Content body
            if text_frame:
                p = text_frame.add_paragraph()
                p.text = stripped
                p.level = 0
                if stripped.startswith('- '):
                    p.text = stripped[2:]
                    p.level = 1
            else:
                # If no slide created yet, create a generic one
                if current_slide is None:
                    layout = prs.slide_layouts[1]
                    current_slide = prs.slides.add_slide(layout)
                    title = current_slide.shapes.title
                    title.text = "Overview"
                    body_shape = current_slide.placeholders[1]
                    text_frame = body_shape.text_frame
                
                p = text_frame.add_paragraph()
                p.text = stripped

def generate_ppt(client_name: str, output_dir: str):
    """
    Generate a PPTX file from the Markdown results in the output_dir.
    """
    output_path = Path(output_dir)
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = f"GEO Report: {client_name}"
    subtitle.text = "Generated by GEO Business Tool"
    
    # Helper to find and parse files
    files = list(output_path.glob("Result_Prompt_*.md"))
    # Sort files to ensure D -> B -> C -> A or alphabetical
    # Usually: Result_Prompt_A.md, Result_Prompt_B.md ...
    # Pipeline order is D, B, C, A.
    # We can try to respect that or just alphabetical.
    # Let's define a priority map
    priority = {'D': 0, 'B': 1, 'C': 2, 'A': 3}
    
    files.sort(key=lambda p: priority.get(p.stem.split('_')[-1], 99))
    
    for md_file in files:
        # Add a section separator for the file
        layout = prs.slide_layouts[2] # Section Header
        slide = prs.slides.add_slide(layout)
        title = slide.shapes.title
        title.text = f"Module: {md_file.stem.replace('Result_Prompt_', '')}"
        
        content = md_file.read_text(encoding='utf-8')
        parse_markdown_to_slides(content, prs)
        
    ppt_path = output_path / f"GEO_Report_{client_name}.pptx"
    prs.save(str(ppt_path))
    return str(ppt_path)

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 2:
        generate_ppt(sys.argv[1], sys.argv[2])
    else:
        print("Usage: python ppt_generator.py <client_name> <output_dir>")
